% boys

male(adam).
male(alan).
male(albert).
male(alexander).
male(allan).
male(andrew).
male(andy).
male(anthony).
male(archie).
male(arnold).
male(arthur).
male(barney).
male(barry).
male(benjamin).
male(bill).
male(bobby).
male(brad).
male(bruce).
male(calvin).
male(carl).
male(charles).
male(christopher).
male(daniel).
male(danny).
male(david).
male(denis).
male(donald).
male(edward).
male(eric).
male(ferdinand).
male(fred).
male(george).
male(greg).
male(gregory).
male(harold).
male(harry).
male(henry).
male(hugo).
male(isaac).
male(ivan).
male(james).
male(jeffrey).
male(jim).
male(john).
male(joseph).
male(karl).
male(ken).
male(kevin).
male(lawrence).
male(louis).
male(mark).
male(max).
male(nathan).
male(ned).
male(neil).
male(nick).
male(otis).
male(patrick).
male(paul).
male(peter).
male(phillip).
male(ralph).
male(ray).
male(rex).
male(richard).
male(robert).
male(roy).
male(ryan).
male(rex).
male(sam).
male(scott).
male(sean).
male(seth).
male(steve).
male(teddy).
male(tim).
male(tom).
male(tyler).
male(victor).
male(vincent).
male(warren).
male(wayne).
male(woody).

% girls

female(abigail).
female(alice).
female(amanda).
female(amy).
female(andrea).
female(ann).
female(april).
female(ashley).
female(barbara).
female(beth).
female(betty).
female(brittany).
female(caroline).
female(cassandra).
female(catherine).
female(christina).
female(clara).
female(cynthia).
female(daisy).
female(deborah).
female(dorothy).
female(elaine).
female(eleanor).
female(elizabeth).
female(eloise).
female(emily).
female(erica).
female(grace).
female(harriet).
female(heidi).
female(helen).
female(holly).
female(honeysha).
female(irene).
female(isabel).
female(jackie).
female(jane).
female(jessica).
female(judy).
female(kate).
female(katherine).
female(laura).
female(lilly).
female(lisa).
female(lois).
female(lorainne).
female(lucy).
female(lynn).
female(madeleine).
female(mary).
female(may).
female(michelle).
female(mimi).
female(molly).
female(monica).
female(nadine).
female(nancy).
female(nina).
female(pearl).
female(penny).
female(rachael).
female(rebecca).
female(rose).
female(roxanne).
female(ruth).
female(sally).
female(samantha).
female(sara).
female(sharon).
female(sophie).
female(susan).
female(sylvia).
female(tiffany).
female(tina).
female(valerie).
female(victoria).
female(virginia).
female(yvonne).

% parents

parent(andrew,brittany).
parent(judy,brittany).
parent(jeffrey,erica).
parent(jeffrey,tyler).
parent(heidi,erica).
parent(heidi,tyler).

parent(nathan,lois).
parent(nathan,alice).
parent(nathan,nick).
parent(nathan,andrew).
parent(harriet,lois).
parent(harriet,alice).
parent(harriet,nick).
parent(harriet,andrew).

parent(susan,heidi).
parent(susan,lisa).
parent(susan,warren).
parent(susan,fred).
parent(kevin,heidi).
parent(kevin,lisa).
parent(kevin,warren).
parent(kevin,fred).

parent(laura,cynthia).
parent(laura,harold).
parent(paul,cynthia).
parent(paul,harold).

parent(ralph,jeffrey).
parent(ralph,judy).
parent(helen,jeffrey).
parent(helen,judy).

parent(abigail,harriet).
parent(hugo,harriet).

parent(peter,nathan).
parent(may,nathan).
parent(peter,susan).
parent(may,susan).

parent(isaac,kevin).
parent(isaac,laura).
parent(andrea,kevin).
parent(andrea,laura).

parent(james,paul).
parent(lucy,paul).

parent(henry,ralph).
parent(betty,ralph).

parent(timothy,isaac).
parent(ann,isaac).

parent(mark,andrea).
parent(barbara,andrea).
parent(mark,james).
parent(barbara,james).

parent(adam,barbara).
parent(adam,henry).
parent(eve,barbara).
parent(eve,henry).

parent(karl,peter).
parent(cassandra,peter).
parent(karl,tom).
parent(cassandra,tom).
parent(karl,daisy).
parent(cassandra,daisy).

parent(lilly,may).
parent(robert,may).
parent(lilly,eleanor).
parent(robert,eleanor).
parent(lilly,seth).
parent(robert,seth).
